### PR TITLE
Add SD card to storage analysis

### LINKED ISSUE #678: Storage analysis for SD card?
Hi,
currently when clicking on "Storage" I get the analysis data for the internal storage, but it seems no way to show it for the external SD card. Or am I overlooking it?

### PR DESCRIPTION
**Pull request by esensar**
This closes #678

### CODE REVIEW

**Comment by tibbi** [comment]
it shows the exact same values for internal storage and SD card too

**Comment by tibbi** [comment]
mimetype sizes like images, videos etc seem to show the same values, it doesnt differ in internal storage and SD card

**Comment by esensar** [comment]
Used wrong volume name for internal storage. It should work as expected now.

**Comment by tibbi** [comment]
nice thanks, looks really good now

**Pull request merged**
