### PR TITLE
Add support for decompressing password protected zips

### PR DESCRIPTION
**Pull request by esensar**
This includes Zip4j library which supports password protected ZIP archives and replaces default zip library in DecompressActivity.

NOTE: This does not cover decompression of multiple ZIPs, since I am not completely sure what UX we would want in that case.

## TODO
- [x] Add Zip4J license to https://github.com/SimpleMobileTools/Simple-Commons and reference it in this app (https://github.com/SimpleMobileTools/Simple-Commons/pull/1724)
- [x] Cover decompressing multiple ZIPs (just addded a better error message)

### CODE REVIEW

**Comment by tibbi** [comment]
no need to cover decompressing multiple files for this initial implementation. Lets just go step by step as always. If you detect multiple password protected zips, just shown the An unknown error occurred.

**Comment by tibbi** [comment]
or lets show Wrong password instead, to at least give the user a hint about what is wrong

**Comment by tibbi** [comment]
lets replace "Error: Incorrect password" with just "Incorrect password"

**Comment by esensar** [comment]
> lets replace "Error: Incorrect password" with just "Incorrect password"

Should the same be done for PDFs then?

**Comment by tibbi** [comment]
yeah, lets keep it human, not that robotic

**Comment by tibbi** [comment]
okay thanks, should be good now

**Pull request merged**
