### PR TITLE
Display search progress bar

### PR DESCRIPTION
**Pull request by sdex**

### CODE REVIEW

**Comment by tibbi** [comment]
remove the top padding from it please, it should be closer to the selected tab indicator. Also make it stop at closing search

**Comment by tibbi** [comment]
1. it gets stuck as you switch to a different tab
2. make sure it uses the accent color at White and B&W theme. Would be good to just use getProperPrimaryColor() color on it and ignore whatever theme we have selected.

**Comment by sdex** [comment]
> 1. it gets stuck as you switch to a different tab
> 
>     2. make sure it uses the accent color at White and B&W theme. Would be good to just use getProperPrimaryColor() color on it and ignore whatever theme we have selected.

I couldn't reproduce the first issue. When I switch the tabs the search field is hidden, and the progress too. 

I added a 250 ms delay before displaying the progress to avoid flickering when the search is fast.

**Comment by tibbi** [comment]
ok thanks, looks good now

**Pull request merged**
