### PR TITLE
Add support for creating password protected zips

### PR DESCRIPTION
**Pull request by esensar**
This one made sense to add since we were adding support for opening password protected ZIPs and the library that was included in that PR (https://github.com/SimpleMobileTools/Simple-File-Manager/pull/720) has that capability already, so it was pretty simple to add.

## TODO
- [x] Wait for https://github.com/SimpleMobileTools/Simple-File-Manager/pull/720 to ensure library is properly integrated first
- [x] Add additional string to Simple-Commons for password protection checkbox (currently it displays just `Password`, it would make more sense to display something like `Protect with password` or something like that)
- [x] Wait for https://github.com/SimpleMobileTools/Simple-Commons/pull/1740 and update Simple-Commons ref
- [ ] Wait for https://github.com/SimpleMobileTools/Simple-Commons/pull/1742 and update Simple-Commons ref to fix eye icon visibility in light theme

### CODE REVIEW

**Comment by esensar** [comment]
I have updated the strings and also added an eye icon for password preview when compressing. If it looks okay, I just need to merge the commons PR (https://github.com/SimpleMobileTools/Simple-Commons/pull/1740) and then update the ref on this PR.

**Comment by tibbi** [comment]
the eye icon isnt visible in light theme

**Comment by esensar** [comment]
I have opened up a PR in Simple-Commons to resolve that: https://github.com/SimpleMobileTools/Simple-Commons/pull/1742

**Comment by tibbi** [comment]
alright thanks, that seems to work just fine

**Pull request merged**
