### PR TITLE
Add toggle to disable "Press back again to exit"

### LINKED ISSUE #468: Remove or toggle "Press back again to exit"
Similar to #356 . "Press back again to exit" is a bit frustrating, I'd like to be able to close the app with a single back button press.

If you want, I can create a PR to implement this feature, either as a toggle or removing the double-back-press entirely. Let me know what would be preferred.

### PR DESCRIPTION
**Pull request by tkterris**
Add toggle to settings activity for the "Press back again to exit" functionality. Defaults to true (current behavior). This fixes #468 .

### CODE REVIEW

**Comment by tibbi** [comment]
change the string to "Require pressing Back twice to leave the app", move it into the Settings section at the strings and avoid translating it to all languages with some translator. Better keep it untranslated.

**Comment by tkterris** [comment]
> change the string to "Require pressing Back twice to leave the app", move it into the Settings section at the strings and avoid translating it to all languages with some translator. Better keep it untranslated.

Done.

**Comment by tibbi** [comment]
I mean replace "Press back twice to exit" with "Require pressing Back twice to leave the app" and add it to every languages file, just keep it untranslated. Also remove the "translatable=false"

**Comment by tkterris** [comment]
> I mean replace "Press back twice to exit" with "Require pressing Back twice to leave the app" and add it to every languages file, just keep it untranslated. Also remove the "translatable=false"

Ah, understood. Done.

**Comment by tibbi** [comment]
ye looks good, you just copypasted some unrelated code without understanding it. Thanks

**Pull request merged**
